import os, sys

# First test
env = Environment(ENV = os.environ, tools = ['Docs.Mkdocs'], toolpath = [PyPackageDir('scons_tools_grbd.Tools')])
env.Replace(Mkdocs_CleanBuild = True)
env.Replace(Mkdocs_Strict = True)
env.Replace(Mkdocs_SiteDir = 'site')
env.Replace(Mkdocs_Quiet = True)
env.Replace(Mkdocs_Verbose = True)
tgt = env.MkdocsJsonBuild()
Default(tgt)

# Test with Node objects
env2 = Environment(ENV = os.environ, tools = ['Docs.Mkdocs'], toolpath = [PyPackageDir('scons_tools_grbd.Tools')])
env2.Replace(Mkdocs_SiteDir = Dir('site2'))
tgt = env2.MkdocsJsonBuild(File('mkdocs.yml'))
Default(tgt)
