site_name: Scons-Tools-Grbd
site_url: http://ASoftTech.github.io/Scons-Tools-Grbd
repo_url: https://github.com/ASoftTech/Scons-Tools-Grbd
site_description: Scons-Tools-Grbd - Tools for scons
edit_uri: edit/master/docs/MkDocs/docs

pages:
- Home: index.md

- Builders:
    - Mkdocs:
        - MkdocsServer : Builders\Mkdocs\MkdocsServer.md
        - MkdocsBuild : Builders\Mkdocs\MkdocsBuild.md
        - MkdocsPublish : Builders\Mkdocs\MkdocsPublish.md
        - MkdocsJsonBuild : Builders\Mkdocs\MkdocsJsonBuild.md
        - MkdocsCombiner : Builders\Mkdocs\MkdocsCombiner.md

#theme: cosmo
theme: cyborg
#theme: alabaster
#theme: readthedocs
#theme: mkdocs
#theme: material

# Overrides content within the selected theme
theme_dir: theme

markdown_extensions:
    - smarty

extra_css:
    - css/highlight-fix.css
    - css/highlight-custom.css
    - css/navbarfix.css
